### ISSUE TITLE
Not enough information  and some disinformation 

### ISSUE THREAD

**Issue by yk-jemmic** [bitovi/react-to-webcomponent#58]
Hi all. First of all, thanks for this small but much-needed library!
During my investigation, I found several inaccuracies and some missing information.

- I use "react-to-webcomponent": "^2.0.0-alpha.0" (probably I should not but...) it would be nice to know some release notes like what major was changed compared to version "1.7.2"  (looks as if it does not corespond reality in the section "Releases" ). curently  I see it is  *.ts insted of *.js
- The "Complete Example" is not complete:
in nutshell, it doesn't work because the "interface GreetingProps" doesn't conform "...ReactComponent: { propTypes?: object },..."

**Comment by Yukooo** [comment]
>  it doesn't work because the "interface GreetingProps" doesn't conform "...ReactComponent: { propTypes?: object },..."
I was wrong . it has other compile issues...

**Comment by janebitovi** [comment]
Thank you for pointing this out, I've drafted releases for the last stable release (including a summary since our previous release draft) and the 2.0.0-alpha release. We'll aim to be more consistent with drafting the releases

https://github.com/bitovi/react-to-webcomponent/releases/tag/v1.7.2

https://github.com/bitovi/react-to-webcomponent/releases/tag/v2.0.0-alpha.0

The compile issues hopefully will be resolved with the `// @ts-ignore` example in the 2 alpha release notes - typings are not complete yet.

Please let us know if this resolves the issues, and thanks again!
